#!/bin/bash -e

function usage {
	echo "Usage: $0 <version> <operating-system>"
	exit 1
}

function build {
	proj=${1}
	ver=${2}

	if [ ! -d ${proj} ]; then
		git clone https://github.com/nildev/api-host
	fi

	cd ${proj}
	git checkout master
	git fetch --all
	git reset --hard origin/master
	git checkout $ver
	./build
	cd -
}

function package {
	proj=${1}
	target=${2}

	ccdir="${proj}/bin/${GOOS}_${GOARCH}"
	if [ -d ${ccdir} ]; then
		cp ${ccdir}/${proj}* ${target}
	else
		cp ${proj}/bin/${proj}* ${target}
	fi

	cp ${proj}/README.md ${target}/README.md
}

VER=$1
GOOS=$2

GOARCH="amd64"

if [ "$GOOS" == "" ]; then
	usage
fi

build api-host ${VER}

TARGET="api-host-${VER}-${GOOS}-${GOARCH}"
mkdir ${TARGET}

package api-host ${TARGET}

if [ ${GOOS} == "windows" ]; then
	zip -r ${TARGET}.zip ${TARGET}
else
	tar cvvfz ${TARGET}.tar.gz ${TARGET}
fi
